name: build-android-debug
on:
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Capacitor copy (web → android)
        run: npx cap copy android

      - name: Capacitor sync (plugins)
        run: npx cap sync android

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Force Gradle 8.6 wrapper (si besoin)
        run: |
          sed -i 's/gradle-[0-9.]\+-\(all\|bin\)\.zip/gradle-8.6-all.zip/' android/gradle/wrapper/gradle-wrapper.properties
          grep distributionUrl android/gradle/wrapper/gradle-wrapper.properties

      - name: Build Android APK (DEBUG, non signé)
        run: cd android && ./gradlew --no-daemon assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-unsigned
          path: android/app/build/outputs/apk/debug/app-debug.apk
